Update linters pypi links to latest version
charliermarsh/ruff pull request #2062
Opened 2023-01-21 16:20 UTC by alonme

I saw that some of the links to the linters PYPI page are not pointing to the latest version - updated those.

BTW - any reason to link to a specific version and not to the latest (https://pypi.org/project/ruff/ instead of https://pypi.org/project/ruff/0.0.228/) ?

2023-01-21 18:05 UTC, charliermarsh commented
Yeah, the versions actually were intentional, since they represent the version at which the plugin was ported over (in the event that they continue to evolve). But, maybe that's just confusing, and not very helpful.

If we do want to change this, though, it needs to be done in Rust files themselves -- so, e.g., we'd need to change this:

```rust
//! Rules from [flake8-tidy-imports](https://pypi.org/project/flake8-tidy-imports/4.8.0/).
```

Then run `cargo dev generate-all` to regenerate the README :)

2023-01-21 19:56 UTC, alonme commented
Ok cool,
I found it confusing - but maybe it just needs to say that explicitly,
So whatever you think is best

2023-01-21 20:10 UTC, charliermarsh commented
I think it's fine to change it, if you don't mind modifying the references in those source files.

2023-01-21 21:43 UTC, alonme commented
by change do you mean update to latest version or delete the version?

2023-01-21 21:47 UTC, charliermarsh commented
Ah sorry, I mean remove the version, and point to latest.

2023-01-22 07:14 UTC, not-my-profile commented
I think it makes sense to remove the versions since if anything we'd have to track the upstream version for each rule individually ... it doesn't make sense to track it for a whole linter.

2023-01-22 07:15 UTC, not-my-profile requested changes
The links should include the trailing `/` because otherwise there's an unnecessary redirect when following these links.

You'll also want to run `cargo dev regenerate-all` to update the links in the README.

2023-01-22 12:40 UTC, sbrugman reviewed
Please also update the `scripts/add_plugin.py` example:
https://github.com/charliermarsh/ruff/blob/main/scripts/add_plugin.py#L8

2023-01-22 15:36 UTC, not-my-profile commented on src/rules/pygrep_hooks/mod.rs
> +//! Rules from [pygrep-hooks](https://github.com/pre-commit/pygrep-hooks/).
nit: but the trailing slash isn't necessary for GitHub

2023-01-22 15:37 UTC, not-my-profile commented on src/rules/flake8_import_conventions/mod.rs
> +//! Rules from [flake8-import-conventions](https://github.com/joaopalmeiro/flake8-import-conventions/).
same here^^

2023-01-22 16:16 UTC, sbrugman commented on scripts/add_plugin.py
> +        --url https://pypi.org/project/flake8-pie/
There is one more reference on line 107

2023-01-22 18:10 UTC, merged

2023-01-22 18:10 UTC, charliermarsh commented
Thanks!