feat: implement TRY200
charliermarsh/ruff pull request #2087
Opened 2023-01-22 14:42 UTC by karpa4o4

2023-01-22 17:59 UTC, charliermarsh commented on src/rules/tryceratops/rules/reraise_no_cause.rs
> +                ));
I think we need to recurse here to handle cases like:

```py
def bad():
    try:
        process()
    except MyException:
        if True:
            raise MainFunctionFailed()
```

This came up in another PR -- here's my explanation: https://github.com/charliermarsh/ruff/pull/2073#discussion_r1083345058

2023-01-22 17:59 UTC, charliermarsh commented on src/rules/tryceratops/rules/reraise_no_cause.rs
> +                ));
(Otherwise, looks good!)

2023-01-22 18:00 UTC, charliermarsh requested changes
Thanks! Think we just need to expand the logic to recurse over the statements.

2023-01-23 18:20 UTC, karpa4o4 commented
> Thanks! Think we just need to expand the logic to recurse over the statements.

Can you describe what statements you are talking about? If as in the screenshot, then it already works.
![Screenshot_20230123_211848](https://user-images.githubusercontent.com/33448939/214118476-d3c0dd8b-0b56-47eb-9a16-68fa521dc30a.png)
![Screenshot_20230123_211641](https://user-images.githubusercontent.com/33448939/214118627-4086e3ec-b108-4895-92ed-8721483183b5.png)

2023-01-23 19:09 UTC, charliermarsh commented
Looks good, I'm gonna rebase then merge.

2023-01-23 19:12 UTC, merged